#!/usr/bin/env bash
#
# Opale — one-line installer.
#
#   curl -fsSL https://opale.pages.dev/install.sh | bash
#
# Interactive: prompts for domain + Microsoft Entra App credentials, generates
# secrets, writes .env, then starts the stack with docker compose.
#
# Prerequisites (checked below): git, openssl, docker, docker compose v2.
#
# Does NOT touch: DNS, TLS, reverse proxy, Entra App Registration. Manual
# steps for those are printed at the end. See INSTALL.md for the long version.
#
# Override defaults via environment:
#   OPALE_REPO_URL     git repository (default: https://github.com/4rtefakt/opale.git)
#   OPALE_INSTALL_DIR  target directory (default: ./opale)
#   OPALE_BRANCH       branch to checkout (default: main)

set -euo pipefail

# When piped via curl | bash, stdin is the pipe (no TTY) and `read` fails.
# Reconnect stdin to the user's terminal so prompts work.
if [[ -t 0 ]]; then :; else
  if [[ -r /dev/tty ]]; then exec < /dev/tty
  else
    echo "ERROR: install.sh requires an interactive terminal." >&2
    echo "       Either run it directly (./install.sh) or pipe with a TTY." >&2
    exit 1
  fi
fi

REPO_URL="${OPALE_REPO_URL:-https://github.com/4rtefakt/opale.git}"
INSTALL_DIR="${OPALE_INSTALL_DIR:-./opale}"
BRANCH="${OPALE_BRANCH:-main}"

# Color helpers — degraded gracefully if TERM doesn't support colors.
if [[ -t 1 ]] && tput colors >/dev/null 2>&1 && [[ $(tput colors) -ge 8 ]]; then
  BOLD=$(tput bold) DIM=$(tput dim) RED=$(tput setaf 1) GREEN=$(tput setaf 2) CYAN=$(tput setaf 6) RESET=$(tput sgr0)
else
  BOLD='' DIM='' RED='' GREEN='' CYAN='' RESET=''
fi
bold() { printf '%s%s%s\n' "$BOLD" "$*" "$RESET"; }
info() { printf '%s▸ %s%s\n' "$CYAN" "$*" "$RESET"; }
ok()   { printf '%s✓ %s%s\n' "$GREEN" "$*" "$RESET"; }
err()  { printf '%s✗ %s%s\n' "$RED" "$*" "$RESET" >&2; }

bold ""
bold "  Opale installer"
printf '%s  https://github.com/4rtefakt/opale%s\n\n' "$DIM" "$RESET"

# ─── 1. Prerequisites ──────────────────────────────────────────────────────
info "Checking prerequisites"
missing=0
for tool in git openssl docker; do
  if ! command -v "$tool" >/dev/null 2>&1; then err "$tool not found"; missing=1; fi
done
if ! docker compose version >/dev/null 2>&1; then err "docker compose v2 not found (docker-compose v1 is not supported)"; missing=1; fi
[[ "$missing" -eq 0 ]] || { err "Install the missing tools and rerun"; exit 1; }
ok "git, openssl, docker, docker compose v2"

# ─── 2. Clone ──────────────────────────────────────────────────────────────
if [[ -d "$INSTALL_DIR" ]]; then
  info "$INSTALL_DIR already exists"
  printf '  Reuse existing directory? [y/N] '
  read -r answer
  [[ "$answer" =~ ^[Yy] ]] || { err "Aborted"; exit 1; }
else
  info "Cloning $REPO_URL → $INSTALL_DIR"
  git clone --depth 1 --branch "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ─── 3. Vendor front-end deps ──────────────────────────────────────────────
info "Vendoring front-end deps (MSAL, xterm, tabler-icons, …)"
bash setup.sh >/dev/null 2>&1 || { err "setup.sh failed — rerun manually for the error"; exit 1; }
ok "Front-end vendors fetched"

# ─── 4. Interactive prompts ────────────────────────────────────────────────
bold ""
bold "Configuration"
printf '\n'
printf '  Public domain (without https://) [opale.example.com]: '
read -r DOMAIN
DOMAIN="${DOMAIN:-opale.example.com}"

bold ""
bold "Microsoft Entra App Registration (see INSTALL.md §3)"
printf '\n'
printf '  Tenant ID: '       ; read -r ENTRA_TENANT
printf '  Client ID: '       ; read -r ENTRA_CLIENT
printf '  Client Secret: '   ; read -rs ENTRA_SECRET; echo

if [[ -z "$ENTRA_TENANT" || -z "$ENTRA_CLIENT" || -z "$ENTRA_SECRET" ]]; then
  err "Entra credentials are required (see INSTALL.md §3 to create the App Registration)"
  exit 1
fi

# ─── 5. Generate secrets ───────────────────────────────────────────────────
info "Generating secrets"
PG_PASS=$(openssl rand -hex 24)
ok "Postgres password: 24-byte hex"

# ─── 6. Write .env ─────────────────────────────────────────────────────────
info "Writing .env (mode 600)"
cat > .env <<EOF
# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Do not commit. Keep secrets in a password manager.

PORT=3010
NODE_ENV=production

POSTGRES_DB=opale
POSTGRES_USER=opale
POSTGRES_PASSWORD=${PG_PASS}
POSTGRES_HOST=db

FRONTEND_URL=https://${DOMAIN}
API_BASE_URL=/api

ENTRA_TENANT_ID=${ENTRA_TENANT}
ENTRA_CLIENT_ID=${ENTRA_CLIENT}
ENTRA_CLIENT_SECRET=${ENTRA_SECRET}

SSH_USER=opale
SSH_PORT=22
SSH_PRIVATE_KEY_B64=

# Web Push (PWA notifications) — generate later with:
#   npx web-push generate-vapid-keys
# Then set VAPID_EMAIL to "mailto:admin@${DOMAIN}".
VAPID_PUBLIC_KEY=
VAPID_PRIVATE_KEY=
VAPID_EMAIL=

ONBOARDING_BASE_GROUP_IDS=
ONBOARDING_LICENSE_GROUP_ID=
EOF
chmod 600 .env
ok ".env written"

# ─── 7. Start the stack ────────────────────────────────────────────────────
info "Starting the stack (docker compose -f docker-compose.example.yml up -d)"
docker compose -f docker-compose.example.yml up -d

# ─── 8. Healthcheck poll ───────────────────────────────────────────────────
info "Waiting for API to respond (up to 60s)"
ready=0
for _ in $(seq 1 60); do
  if curl -sf "http://localhost:3010/env.js" >/dev/null 2>&1; then ready=1; break; fi
  sleep 1
done
if [[ "$ready" -eq 1 ]]; then ok "API responding on :3010"
else err "API did not respond within 60s — check 'docker compose logs api'"; fi

# ─── 9. Next steps ─────────────────────────────────────────────────────────
bold ""
bold "✓ Installation complete"
cat <<EOF

${DIM}Next steps:${RESET}

  ${BOLD}1.${RESET} Point a reverse proxy (Caddy / nginx / Traefik) at ${BOLD}localhost:3010${RESET}
     for ${BOLD}${DOMAIN}${RESET} with a valid TLS certificate. Example Caddyfile:

         ${DOMAIN} {
             reverse_proxy localhost:3010
         }

  ${BOLD}2.${RESET} In Entra → API permissions, grant admin consent for the application.

  ${BOLD}3.${RESET} Open ${BOLD}https://${DOMAIN}${RESET} and sign in. Your account becomes the
     first admin automatically.

  ${BOLD}4.${RESET} Build the Windows agent:
         node agent-go/build.js --url https://${DOMAIN}

  ${BOLD}5.${RESET} (Optional) Enable Web Push notifications:
         npx web-push generate-vapid-keys
         # Add VAPID_PUBLIC_KEY / VAPID_PRIVATE_KEY / VAPID_EMAIL to .env, then:
         docker compose -f docker-compose.example.yml restart api

${DIM}Logs:${RESET}       docker compose -f docker-compose.example.yml logs -f api
${DIM}Backup .env:${RESET} cp .env .env.backup.\$(date +%s)
${DIM}Full docs:${RESET}  ${INSTALL_DIR}/INSTALL.md
EOF
